
services:
  jenkins:
    build: ./jenkins
    image: examle-jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jcasc:/var/jcasc
    environment:
      - JENKINS_URL=http://jenkins:8080
      - CASC_JENKINS_CONFIG=/var/jcasc
    networks:
      - jenkins-net
    restart: always

  agent:
    image: jenkins/inbound-agent:latest-jdk11
    container_name: agent
    command: -url http://jenkins:8080/ -workDir=/home/jenkins/agent -secret ${JENKINS_AGENT_SECRET} -name agent
    init: true
    networks:
      - jenkins-net
    restart: always


volumes:
  jenkins_home:


networks:
  jenkins-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.32.9.0/24
